package org.d0sl.model.expression;

/**
 * Enumerates expressions types
 *
 * @version %I%,%G%
 */
public enum ExpressionType {
    NUMERIC_TERM, NUMERIC_CONSTANT,
    LOGICAL_AND, PREDICATE_CALL, LOGICAL_COMPARISON,
    LOGICAL_IMPLICATION, LOGICAL_NOT, LOGICAL_OR, LOGICAL_CONSTANT,
    STRING_TERM, STRING_CONSTANT, FUNCTION_CALL, LIST, FOR_ALL, RANGE_REF,
    VARIABLE_REF, PARENTHESES, ARGUMENT_REF, LOGGING, BASE_OBJECT
}
